spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog.yml


  jpa:
    hibernate:
      ddl-auto : create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl