spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog.yml


  jpa:
    show-sql: true
    hibernate:
      ddl-auto : create-drop