spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog.yml


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp-mail.outlook.com
    username: careers@VigyanShaala.com
    password: jjttjhlnxshmjdkb
    properties:
      mail:
        store:
          protocol: pop3
        smtp:
          ssl:
            trust: smtp-mail.outlook.com
          auth: true
          starttls:
            enable: true